package csharp

const fileTpl = `// <auto-generated>
//   This file was generated by protoc-gen-validate
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;

namespace {{ csharpNamespace .File }}
{
	/// <summary>
	/// Validator for protobuf messages defined in {{ .File.Name }}
	/// </summary>
	public static class {{ classNameFile . }}Validator
	{
		{{ range .AllMessages -}}
		{{- template "msg" . -}}
		{{ end }}

		{{ template "utils" }}
	}

	{{ template "exception" }}
}
}
`
